/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as DashboardTrackRouteImport } from './routes/dashboard.track'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardCartRouteImport } from './routes/dashboard.cart'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProductsRoute,
} as any)
const DashboardTrackRoute = DashboardTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCartRoute = DashboardCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/products': typeof ProductsRouteWithChildren
  '/register': typeof RegisterRoute
  '/dashboard/cart': typeof DashboardCartRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/track': typeof DashboardTrackRoute
  '/products/$id': typeof ProductsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/products': typeof ProductsRouteWithChildren
  '/register': typeof RegisterRoute
  '/dashboard/cart': typeof DashboardCartRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/track': typeof DashboardTrackRoute
  '/products/$id': typeof ProductsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/products': typeof ProductsRouteWithChildren
  '/register': typeof RegisterRoute
  '/dashboard/cart': typeof DashboardCartRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/track': typeof DashboardTrackRoute
  '/products/$id': typeof ProductsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/products'
    | '/register'
    | '/dashboard/cart'
    | '/dashboard/orders'
    | '/dashboard/profile'
    | '/dashboard/track'
    | '/products/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/products'
    | '/register'
    | '/dashboard/cart'
    | '/dashboard/orders'
    | '/dashboard/profile'
    | '/dashboard/track'
    | '/products/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/products'
    | '/register'
    | '/dashboard/cart'
    | '/dashboard/orders'
    | '/dashboard/profile'
    | '/dashboard/track'
    | '/products/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/dashboard/track': {
      id: '/dashboard/track'
      path: '/track'
      fullPath: '/dashboard/track'
      preLoaderRoute: typeof DashboardTrackRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cart': {
      id: '/dashboard/cart'
      path: '/cart'
      fullPath: '/dashboard/cart'
      preLoaderRoute: typeof DashboardCartRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardCartRoute: typeof DashboardCartRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardTrackRoute: typeof DashboardTrackRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCartRoute: DashboardCartRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardTrackRoute: DashboardTrackRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ProductsRouteChildren {
  ProductsIdRoute: typeof ProductsIdRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsIdRoute: ProductsIdRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ProductsRoute: ProductsRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
